services:
  api:
    build: .
    container_name: pets-api
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  db:
      image: mysql:8.0
      restart: always
      environment:
        SPRING_PROFILES_ACTIVE: local
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - ./sql/sql_mysql.sql:/docker-entrypoint-initdb.d/sql_mysql.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db